### ISSUE TITLE
Mark as flake!

### ISSUE THREAD

**Issue by marissarcollins** [bullhorn/automation-dashboard#21]
# Feature  Request
Allow the ability to mark a test as a flake/passed/passing locally which will change its status away from failed
# Added Value
You can mark that a test is passing if you are running a single test locally or manually instead of having to rerun the whole Jenkins suite
# Proposed Solutions
   I don't know ¯\_(ツ)_/¯

**Comment by bulbajackel** [comment]
Will this just be for the day? Not a flag that will be set permanently.  Only 'til the next test run?

**Comment by rohitmahatma** [comment]
@marissarcollins You can pass "--params.dashboard.scrape=true" for Novo and "-DDASHBOARD=scrape" for S Release when you are running individual test(s) locally to update the dashboard result for the test(s), just like our jenkins jobs do for suites. It was decided on purpose to NOT have more than the four status that we currently have - Pass, Fail, Bug or Pending. Also, we should be looking for solutions to make the test stable rather adding more statuses to dashboard.
